// !!!!!!Lucas, dont read this please <-- facts
// NOTE: If you read this, DONT edit this file, its for our own safety, trust me,
// -im an engineer
// -NOOOOOOOOOOOOOOO
// All this gona be from Lucas when he pushes so its gona look weird af, he talking to himself
const c = @cImport({
    @cDefine("XR_USE_GRAPHICS_API_VULKAN", "1");
    @cDefine("XR_EXTENSION_PROTOTYPES", "1");
    @cInclude("vulkan/vulkan.h");
    @cInclude("openxr/openxr.h");
    @cInclude("openxr/openxr_platform.h");
});
pub usingnamespace c;

pub inline fn check(result: c_int, err: anyerror) !void { // nice
    wrapXR(result) catch |e| @import("std").log.err("{}: {}", .{ err, e });
    return switch (result) {
        0 => err,
        else => wrapXR(result),
    };
}

// Not needed for now, but usefull!
pub fn wrapXR(code: c_int) !void {
    return switch (code) {
        c.XR_ERROR_VALIDATION_FAILURE => error.ValidationFailure,
        c.XR_ERROR_RUNTIME_FAILURE => error.RuntimeFailure,
        c.XR_ERROR_OUT_OF_MEMORY => error.OutOfMemory,
        c.XR_ERROR_API_VERSION_UNSUPPORTED => error.ApiVersionUnsupported,
        c.XR_ERROR_INITIALIZATION_FAILED => error.InitializationFailed,
        c.XR_ERROR_FUNCTION_UNSUPPORTED => error.FunctionUnsupported,
        c.XR_ERROR_FEATURE_UNSUPPORTED => error.FeatureUnsupported,
        c.XR_ERROR_EXTENSION_NOT_PRESENT => error.ExtensionNotPresent,
        c.XR_ERROR_LIMIT_REACHED => error.LimitReached,
        c.XR_ERROR_SIZE_INSUFFICIENT => error.SizeInsufficient,
        c.XR_ERROR_HANDLE_INVALID => error.HandleInvalid,
        c.XR_ERROR_INSTANCE_LOST => error.InstanceLost,
        c.XR_ERROR_SESSION_RUNNING => error.SessionRunning,
        c.XR_ERROR_SESSION_NOT_RUNNING => error.SessionNotRunning,
        c.XR_ERROR_SESSION_LOST => error.SessionLost,
        c.XR_ERROR_SYSTEM_INVALID => error.SystemInvalid,
        c.XR_ERROR_PATH_INVALID => error.PathInvalid,
        c.XR_ERROR_PATH_COUNT_EXCEEDED => error.PathCountExceeded,
        c.XR_ERROR_PATH_FORMAT_INVALID => error.PathFormatInvalid,
        c.XR_ERROR_PATH_UNSUPPORTED => error.PathUnsupported,
        c.XR_ERROR_LAYER_INVALID => error.LayerInvalid,
        c.XR_ERROR_LAYER_LIMIT_EXCEEDED => error.LayerLimitExceeded,
        c.XR_ERROR_SWAPCHAIN_RECT_INVALID => error.SwapchainRectInvalid,
        c.XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED => error.SwapchainFormatUnsupported,
        c.XR_ERROR_ACTION_TYPE_MISMATCH => error.ActionTypeMismatch,
        c.XR_ERROR_SESSION_NOT_READY => error.SessionNotReady,
        c.XR_ERROR_SESSION_NOT_STOPPING => error.SessionNotStopping,
        c.XR_ERROR_TIME_INVALID => error.TimeInvalid,
        c.XR_ERROR_REFERENCE_SPACE_UNSUPPORTED => error.ReferenceSpaceUnsupported,
        c.XR_ERROR_FILE_ACCESS_ERROR => error.FileAccessError,
        c.XR_ERROR_FILE_CONTENTS_INVALID => error.FileContentsInvalid,
        c.XR_ERROR_FORM_FACTOR_UNSUPPORTED => error.FormFactorUnsupported,
        c.XR_ERROR_FORM_FACTOR_UNAVAILABLE => error.FormFactorUnavailable,
        c.XR_ERROR_API_LAYER_NOT_PRESENT => error.ApiLayerNotPresent,
        c.XR_ERROR_CALL_ORDER_INVALID => error.CallOrderInvalid,
        c.XR_ERROR_GRAPHICS_DEVICE_INVALID => error.GraphicsDeviceInvalid,
        c.XR_ERROR_POSE_INVALID => error.PoseInvalid,
        c.XR_ERROR_INDEX_OUT_OF_RANGE => error.IndexOutOfRange,
        c.XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED => error.ViewConfigurationTypeUnsupported,
        c.XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED => error.EnvironmentBlendModeUnsupported,
        c.XR_ERROR_NAME_DUPLICATED => error.NameDuplicated,
        c.XR_ERROR_NAME_INVALID => error.NameInvalid,
        c.XR_ERROR_ACTIONSET_NOT_ATTACHED => error.ActionsetNotAttached,
        c.XR_ERROR_ACTIONSETS_ALREADY_ATTACHED => error.ActionsetsAlreadyAttached,
        c.XR_ERROR_LOCALIZED_NAME_DUPLICATED => error.LocalizedNameDuplicated,
        c.XR_ERROR_LOCALIZED_NAME_INVALID => error.LocalizedNameInvalid,
        c.XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING => error.GraphicsRequirementsCallMissing,
        c.XR_ERROR_RUNTIME_UNAVAILABLE => error.RuntimeUnavailable,
        c.XR_ERROR_EXTENSION_DEPENDENCY_NOT_ENABLED => error.ExtensionDependencyNotEnabled,
        c.XR_ERROR_PERMISSION_INSUFFICIENT => error.PermissionInsufficient,
        c.XR_ERROR_ANDROID_THREAD_SETTINGS_ID_INVALID_KHR => error.AndroidThreadSettingsIdInvalidKhr,
        c.XR_ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR => error.AndroidThreadSettingsFailureKhr,
        c.XR_ERROR_CREATE_SPATIAL_ANCHOR_FAILED_MSFT => error.CreateSpatialAnchorFailedMsft,
        c.XR_ERROR_SECONDARY_VIEW_CONFIGURATION_TYPE_NOT_ENABLED_MSFT => error.SecondaryViewConfigurationTypeNotEnabledMsft,
        c.XR_ERROR_CONTROLLER_MODEL_KEY_INVALID_MSFT => error.ControllerModelKeyInvalidMsft,
        c.XR_ERROR_REPROJECTION_MODE_UNSUPPORTED_MSFT => error.ReprojectionModeUnsupportedMsft,
        c.XR_ERROR_COMPUTE_NEW_SCENE_NOT_COMPLETED_MSFT => error.ComputeNewSceneNotCompletedMsft,
        c.XR_ERROR_SCENE_COMPONENT_ID_INVALID_MSFT => error.SceneComponentIdInvalidMsft,
        c.XR_ERROR_SCENE_COMPONENT_TYPE_MISMATCH_MSFT => error.SceneComponentTypeMismatchMsft,
        c.XR_ERROR_SCENE_MESH_BUFFER_ID_INVALID_MSFT => error.SceneMeshBufferIdInvalidMsft,
        c.XR_ERROR_SCENE_COMPUTE_FEATURE_INCOMPATIBLE_MSFT => error.SceneComputeFeatureIncompatibleMsft,
        c.XR_ERROR_SCENE_COMPUTE_CONSISTENCY_MISMATCH_MSFT => error.SceneComputeConsistencyMismatchMsft,
        c.XR_ERROR_DISPLAY_REFRESH_RATE_UNSUPPORTED_FB => error.DisplayRefreshRateUnsupportedFb,
        c.XR_ERROR_COLOR_SPACE_UNSUPPORTED_FB => error.ColorSpaceUnsupportedFb,
        c.XR_ERROR_SPACE_COMPONENT_NOT_SUPPORTED_FB => error.SpaceComponentNotSupportedFb,
        c.XR_ERROR_SPACE_COMPONENT_NOT_ENABLED_FB => error.SpaceComponentNotEnabledFb,
        c.XR_ERROR_SPACE_COMPONENT_STATUS_PENDING_FB => error.SpaceComponentStatusPendingFb,
        c.XR_ERROR_SPACE_COMPONENT_STATUS_ALREADY_SET_FB => error.SpaceComponentStatusAlreadySetFb,
        c.XR_ERROR_UNEXPECTED_STATE_PASSTHROUGH_FB => error.UnexpectedStatePassthroughFb,
        c.XR_ERROR_FEATURE_ALREADY_CREATED_PASSTHROUGH_FB => error.FeatureAlreadyCreatedPassthroughFb,
        c.XR_ERROR_FEATURE_REQUIRED_PASSTHROUGH_FB => error.FeatureRequiredPassthroughFb,
        c.XR_ERROR_NOT_PERMITTED_PASSTHROUGH_FB => error.NotPermittedPassthroughFb,
        c.XR_ERROR_INSUFFICIENT_RESOURCES_PASSTHROUGH_FB => error.InsufficientResourcesPassthroughFb,
        c.XR_ERROR_UNKNOWN_PASSTHROUGH_FB => error.UnknownPassthroughFb,
        c.XR_ERROR_RENDER_MODEL_KEY_INVALID_FB => error.RenderModelKeyInvalidFb,
        c.XR_ERROR_MARKER_NOT_TRACKED_VARJO => error.MarkerNotTrackedVarjo,
        c.XR_ERROR_MARKER_ID_INVALID_VARJO => error.MarkerIdInvalidVarjo,
        c.XR_ERROR_MARKER_DETECTOR_PERMISSION_DENIED_ML => error.MarkerDetectorPermissionDeniedMl,
        c.XR_ERROR_MARKER_DETECTOR_LOCATE_FAILED_ML => error.MarkerDetectorLocateFailedMl,
        c.XR_ERROR_MARKER_DETECTOR_INVALID_DATA_QUERY_ML => error.MarkerDetectorInvalidDataQueryMl,
        c.XR_ERROR_MARKER_DETECTOR_INVALID_CREATE_INFO_ML => error.MarkerDetectorInvalidCreateInfoMl,
        c.XR_ERROR_MARKER_INVALID_ML => error.MarkerInvalidMl,
        c.XR_ERROR_LOCALIZATION_MAP_INCOMPATIBLE_ML => error.LocalizationMapIncompatibleMl,
        c.XR_ERROR_LOCALIZATION_MAP_UNAVAILABLE_ML => error.LocalizationMapUnavailableMl,
        c.XR_ERROR_LOCALIZATION_MAP_FAIL_ML => error.LocalizationMapFailMl,
        c.XR_ERROR_LOCALIZATION_MAP_IMPORT_EXPORT_PERMISSION_DENIED_ML => error.LocalizationMapImportExportPermissionDeniedMl,
        c.XR_ERROR_LOCALIZATION_MAP_PERMISSION_DENIED_ML => error.LocalizationMapPermissionDeniedMl,
        c.XR_ERROR_LOCALIZATION_MAP_ALREADY_EXISTS_ML => error.LocalizationMapAlreadyExistsMl,
        c.XR_ERROR_LOCALIZATION_MAP_CANNOT_EXPORT_CLOUD_MAP_ML => error.LocalizationMapCannotExportCloudMapMl,
        c.XR_ERROR_SPATIAL_ANCHORS_PERMISSION_DENIED_ML => error.SpatialAnchorsPermissionDeniedMl,
        c.XR_ERROR_SPATIAL_ANCHORS_NOT_LOCALIZED_ML => error.SpatialAnchorsNotLocalizedMl,
        c.XR_ERROR_SPATIAL_ANCHORS_OUT_OF_MAP_BOUNDS_ML => error.SpatialAnchorsOutOfMapBoundsMl,
        c.XR_ERROR_SPATIAL_ANCHORS_SPACE_NOT_LOCATABLE_ML => error.SpatialAnchorsSpaceNotLocatableMl,
        c.XR_ERROR_SPATIAL_ANCHORS_ANCHOR_NOT_FOUND_ML => error.SpatialAnchorsAnchorNotFoundMl,
        c.XR_ERROR_SPATIAL_ANCHOR_NAME_NOT_FOUND_MSFT => error.SpatialAnchorNameNotFoundMsft,
        c.XR_ERROR_SPATIAL_ANCHOR_NAME_INVALID_MSFT => error.SpatialAnchorNameInvalidMsft,
        c.XR_ERROR_SPACE_MAPPING_INSUFFICIENT_FB => error.SpaceMappingInsufficientFb,
        c.XR_ERROR_SPACE_LOCALIZATION_FAILED_FB => error.SpaceLocalizationFailedFb,
        c.XR_ERROR_SPACE_NETWORK_TIMEOUT_FB => error.SpaceNetworkTimeoutFb,
        c.XR_ERROR_SPACE_NETWORK_REQUEST_FAILED_FB => error.SpaceNetworkRequestFailedFb,
        c.XR_ERROR_SPACE_CLOUD_STORAGE_DISABLED_FB => error.SpaceCloudStorageDisabledFb,
        c.XR_ERROR_PASSTHROUGH_COLOR_LUT_BUFFER_SIZE_MISMATCH_META => error.PassthroughColorLutBufferSizeMismatchMeta,
        c.XR_ERROR_HINT_ALREADY_SET_QCOM => error.HintAlreadySetQcom,
        c.XR_ERROR_NOT_AN_ANCHOR_HTC => error.NotAnAnchorHtc,
        c.XR_ERROR_SPACE_NOT_LOCATABLE_EXT => error.SpaceNotLocatableExt,
        c.XR_ERROR_PLANE_DETECTION_PERMISSION_DENIED_EXT => error.PlaneDetectionPermissionDeniedExt,
        c.XR_ERROR_FUTURE_PENDING_EXT => error.FuturePendingExt,
        c.XR_ERROR_FUTURE_INVALID_EXT => error.FutureInvalidExt,
        c.XR_ERROR_SYSTEM_NOTIFICATION_PERMISSION_DENIED_ML => error.SystemNotificationPermissionDeniedMl,
        c.XR_ERROR_SYSTEM_NOTIFICATION_INCOMPATIBLE_SKU_ML => error.SystemNotificationIncompatibleSkuMl,
        c.XR_ERROR_WORLD_MESH_DETECTOR_PERMISSION_DENIED_ML => error.WorldMeshDetectorPermissionDeniedMl,
        c.XR_ERROR_WORLD_MESH_DETECTOR_SPACE_NOT_LOCATABLE_ML => error.WorldMeshDetectorSpaceNotLocatableMl,
        c.XR_ERROR_FACIAL_EXPRESSION_PERMISSION_DENIED_ML => error.FacialExpressionPermissionDeniedMl,
        c.XR_ERROR_COLOCATION_DISCOVERY_NETWORK_FAILED_META => error.ColocationDiscoveryNetworkFailedMeta,
        c.XR_ERROR_COLOCATION_DISCOVERY_NO_DISCOVERY_METHOD_META => error.ColocationDiscoveryNoDiscoveryMethodMeta,
        c.XR_ERROR_SPACE_GROUP_NOT_FOUND_META => error.SpaceGroupNotFoundMeta,
        // c.XR_ERROR_EXTENSION_DEPENDENCY_NOT_ENABLED_KHR => error.ExtensionDependencyNotEnabledKhr,
        // c.XR_ERROR_PERMISSION_INSUFFICIENT_KHR => error.PermissionInsufficientKhr,
        else => {},
    };
}
